version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: tutti
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  app:
    build: ./app
    restart: always

